# Generated by Django 5.2.1 on 2025-05-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('precipitation', models.FloatField()),
                ('event_type', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=20)),
            ],
        ),
    ]
